/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MuscleGroup = IDL.Text;
export const ReadinessItem = IDL.Record({
  'recoveryPct' : IDL.Nat,
  'muscleGroup' : MuscleGroup,
});
export const CoachRecommendation = IDL.Record({
  'workoutType' : IDL.Text,
  'readiness' : IDL.Vec(ReadinessItem),
  'reason' : IDL.Text,
});
export const ExerciseId = IDL.Text;
export const Exercise = IDL.Record({
  'id' : ExerciseId,
  'movement' : IDL.Text,
  'name' : IDL.Text,
  'muscleGroup' : MuscleGroup,
});
export const Timestamp = IDL.Int;
export const PersonalBest = IDL.Record({
  'weight' : IDL.Float64,
  'exerciseId' : ExerciseId,
  'reps' : IDL.Nat,
  'achievedAt' : Timestamp,
  'est1RM' : IDL.Float64,
});
export const RejectedExercise = IDL.Record({
  'exerciseId' : ExerciseId,
  'reason' : IDL.Text,
});
export const SelectionStep = IDL.Record({
  'output' : IDL.Text,
  'step' : IDL.Text,
  'input' : IDL.Text,
});
export const EngineTrace = IDL.Record({
  'rejectedExercises' : IDL.Vec(RejectedExercise),
  'selectionSteps' : IDL.Vec(SelectionStep),
  'fatigueScore' : IDL.Nat,
  'finalOrderingReason' : IDL.Text,
  'phase' : IDL.Text,
  'muscleScores' : IDL.Vec(IDL.Tuple(MuscleGroup, IDL.Float64)),
  'selectedFocus' : IDL.Vec(MuscleGroup),
});
export const SmartExercise = IDL.Record({
  'movement' : IDL.Text,
  'repRange' : IDL.Text,
  'exerciseId' : ExerciseId,
  'coachTip' : IDL.Text,
  'progressionFlag' : IDL.Text,
  'name' : IDL.Text,
  'sets' : IDL.Nat,
  'muscleGroup' : MuscleGroup,
  'targetWeight' : IDL.Float64,
});
export const SmartMenuResult = IDL.Record({
  'trace' : EngineTrace,
  'workout' : IDL.Vec(SmartExercise),
});
export const TrainingState = IDL.Record({
  'fatigueScore' : IDL.Nat,
  'weekNumber' : IDL.Nat,
});
export const ExperienceLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const Goal = IDL.Variant({
  'quick' : IDL.Null,
  'strength' : IDL.Null,
  'hypertrophy' : IDL.Null,
});
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const UserProfile = IDL.Record({
  'experienceLevel' : ExperienceLevel,
  'goal' : Goal,
  'bodyweightKg' : IDL.Float64,
  'gender' : Gender,
  'restTimerSeconds' : IDL.Nat,
});
export const SetLog = IDL.Record({
  'rpe' : IDL.Opt(IDL.Nat),
  'setNumber' : IDL.Nat,
  'weightUsed' : IDL.Float64,
  'repsCompleted' : IDL.Nat,
});
export const WorkoutSession = IDL.Record({
  'setLogs' : IDL.Vec(IDL.Tuple(ExerciseId, IDL.Vec(SetLog))),
  'totalVolume' : IDL.Float64,
  'note' : IDL.Text,
  'exercises' : IDL.Vec(SmartExercise),
  'timestamp' : Timestamp,
  'workoutType' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getCoachRecommendation' : IDL.Func([], [IDL.Opt(CoachRecommendation)], []),
  'getExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getPersonalBests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PersonalBest))],
      [],
    ),
  'getReadiness' : IDL.Func([], [IDL.Vec(ReadinessItem)], []),
  'getSmartMenu' : IDL.Func([IDL.Text], [SmartMenuResult], []),
  'getTrainingState' : IDL.Func([], [IDL.Opt(TrainingState)], []),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getWorkoutHistory' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(WorkoutSession)],
      [],
    ),
  'logWorkout' : IDL.Func([WorkoutSession], [Result], []),
  'setUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MuscleGroup = IDL.Text;
  const ReadinessItem = IDL.Record({
    'recoveryPct' : IDL.Nat,
    'muscleGroup' : MuscleGroup,
  });
  const CoachRecommendation = IDL.Record({
    'workoutType' : IDL.Text,
    'readiness' : IDL.Vec(ReadinessItem),
    'reason' : IDL.Text,
  });
  const ExerciseId = IDL.Text;
  const Exercise = IDL.Record({
    'id' : ExerciseId,
    'movement' : IDL.Text,
    'name' : IDL.Text,
    'muscleGroup' : MuscleGroup,
  });
  const Timestamp = IDL.Int;
  const PersonalBest = IDL.Record({
    'weight' : IDL.Float64,
    'exerciseId' : ExerciseId,
    'reps' : IDL.Nat,
    'achievedAt' : Timestamp,
    'est1RM' : IDL.Float64,
  });
  const RejectedExercise = IDL.Record({
    'exerciseId' : ExerciseId,
    'reason' : IDL.Text,
  });
  const SelectionStep = IDL.Record({
    'output' : IDL.Text,
    'step' : IDL.Text,
    'input' : IDL.Text,
  });
  const EngineTrace = IDL.Record({
    'rejectedExercises' : IDL.Vec(RejectedExercise),
    'selectionSteps' : IDL.Vec(SelectionStep),
    'fatigueScore' : IDL.Nat,
    'finalOrderingReason' : IDL.Text,
    'phase' : IDL.Text,
    'muscleScores' : IDL.Vec(IDL.Tuple(MuscleGroup, IDL.Float64)),
    'selectedFocus' : IDL.Vec(MuscleGroup),
  });
  const SmartExercise = IDL.Record({
    'movement' : IDL.Text,
    'repRange' : IDL.Text,
    'exerciseId' : ExerciseId,
    'coachTip' : IDL.Text,
    'progressionFlag' : IDL.Text,
    'name' : IDL.Text,
    'sets' : IDL.Nat,
    'muscleGroup' : MuscleGroup,
    'targetWeight' : IDL.Float64,
  });
  const SmartMenuResult = IDL.Record({
    'trace' : EngineTrace,
    'workout' : IDL.Vec(SmartExercise),
  });
  const TrainingState = IDL.Record({
    'fatigueScore' : IDL.Nat,
    'weekNumber' : IDL.Nat,
  });
  const ExperienceLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const Goal = IDL.Variant({
    'quick' : IDL.Null,
    'strength' : IDL.Null,
    'hypertrophy' : IDL.Null,
  });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const UserProfile = IDL.Record({
    'experienceLevel' : ExperienceLevel,
    'goal' : Goal,
    'bodyweightKg' : IDL.Float64,
    'gender' : Gender,
    'restTimerSeconds' : IDL.Nat,
  });
  const SetLog = IDL.Record({
    'rpe' : IDL.Opt(IDL.Nat),
    'setNumber' : IDL.Nat,
    'weightUsed' : IDL.Float64,
    'repsCompleted' : IDL.Nat,
  });
  const WorkoutSession = IDL.Record({
    'setLogs' : IDL.Vec(IDL.Tuple(ExerciseId, IDL.Vec(SetLog))),
    'totalVolume' : IDL.Float64,
    'note' : IDL.Text,
    'exercises' : IDL.Vec(SmartExercise),
    'timestamp' : Timestamp,
    'workoutType' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    'getCoachRecommendation' : IDL.Func([], [IDL.Opt(CoachRecommendation)], []),
    'getExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getPersonalBests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PersonalBest))],
        [],
      ),
    'getReadiness' : IDL.Func([], [IDL.Vec(ReadinessItem)], []),
    'getSmartMenu' : IDL.Func([IDL.Text], [SmartMenuResult], []),
    'getTrainingState' : IDL.Func([], [IDL.Opt(TrainingState)], []),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getWorkoutHistory' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(WorkoutSession)],
        [],
      ),
    'logWorkout' : IDL.Func([WorkoutSession], [Result], []),
    'setUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };