/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoachRecommendation {
  'workoutType' : string,
  'readiness' : Array<ReadinessItem>,
  'reason' : string,
}
export interface EngineTrace {
  'rejectedExercises' : Array<RejectedExercise>,
  'selectionSteps' : Array<SelectionStep>,
  'fatigueScore' : bigint,
  'finalOrderingReason' : string,
  'phase' : string,
  'muscleScores' : Array<[MuscleGroup, number]>,
  'selectedFocus' : Array<MuscleGroup>,
}
export interface Exercise {
  'id' : ExerciseId,
  'movement' : string,
  'name' : string,
  'muscleGroup' : MuscleGroup,
}
export type ExerciseId = string;
export type ExperienceLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type Gender = { 'female' : null } |
  { 'male' : null };
export type Goal = { 'quick' : null } |
  { 'strength' : null } |
  { 'hypertrophy' : null };
export type MuscleGroup = string;
export interface PersonalBest {
  'weight' : number,
  'exerciseId' : ExerciseId,
  'reps' : bigint,
  'achievedAt' : Timestamp,
  'est1RM' : number,
}
export interface ReadinessItem {
  'recoveryPct' : bigint,
  'muscleGroup' : MuscleGroup,
}
export interface RejectedExercise {
  'exerciseId' : ExerciseId,
  'reason' : string,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface SelectionStep {
  'output' : string,
  'step' : string,
  'input' : string,
}
export interface SetLog {
  'rpe' : [] | [bigint],
  'setNumber' : bigint,
  'weightUsed' : number,
  'repsCompleted' : bigint,
}
export interface SmartExercise {
  'movement' : string,
  'repRange' : string,
  'exerciseId' : ExerciseId,
  'coachTip' : string,
  'progressionFlag' : string,
  'name' : string,
  'sets' : bigint,
  'muscleGroup' : MuscleGroup,
  'targetWeight' : number,
}
export interface SmartMenuResult {
  'trace' : EngineTrace,
  'workout' : Array<SmartExercise>,
}
export type Timestamp = bigint;
export interface TrainingState {
  'fatigueScore' : bigint,
  'weekNumber' : bigint,
}
export interface UserProfile {
  'experienceLevel' : ExperienceLevel,
  'goal' : Goal,
  'bodyweightKg' : number,
  'gender' : Gender,
  'restTimerSeconds' : bigint,
}
export interface WorkoutSession {
  'setLogs' : Array<[ExerciseId, Array<SetLog>]>,
  'totalVolume' : number,
  'note' : string,
  'exercises' : Array<SmartExercise>,
  'timestamp' : Timestamp,
  'workoutType' : string,
}
export interface _SERVICE {
  'getCoachRecommendation' : ActorMethod<[], [] | [CoachRecommendation]>,
  'getExercises' : ActorMethod<[], Array<Exercise>>,
  'getPersonalBests' : ActorMethod<[], Array<[string, PersonalBest]>>,
  'getReadiness' : ActorMethod<[], Array<ReadinessItem>>,
  'getSmartMenu' : ActorMethod<[string], SmartMenuResult>,
  'getTrainingState' : ActorMethod<[], [] | [TrainingState]>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getWorkoutHistory' : ActorMethod<[bigint, bigint], Array<WorkoutSession>>,
  'logWorkout' : ActorMethod<[WorkoutSession], Result>,
  'setUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];