/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    id: ExerciseId;
    movement: string;
    name: string;
    muscleGroup: MuscleGroup;
}
export interface SmartMenuResult {
    trace: EngineTrace;
    workout: Array<SmartExercise>;
}
export type Timestamp = bigint;
export interface SmartExercise {
    movement: string;
    repRange: string;
    exerciseId: ExerciseId;
    coachTip: string;
    progressionFlag: string;
    name: string;
    sets: bigint;
    muscleGroup: MuscleGroup;
    targetWeight: number;
}
export interface RejectedExercise {
    exerciseId: ExerciseId;
    reason: string;
}
export interface WorkoutSession {
    setLogs: Array<[ExerciseId, Array<SetLog>]>;
    totalVolume: number;
    note: string;
    exercises: Array<SmartExercise>;
    timestamp: Timestamp;
    workoutType: string;
}
export interface EngineTrace {
    rejectedExercises: Array<RejectedExercise>;
    selectionSteps: Array<SelectionStep>;
    fatigueScore: bigint;
    finalOrderingReason: string;
    phase: string;
    muscleScores: Array<[MuscleGroup, number]>;
    selectedFocus: Array<MuscleGroup>;
}
export interface PersonalBest {
    weight: number;
    exerciseId: ExerciseId;
    reps: bigint;
    achievedAt: Timestamp;
    est1RM: number;
}
export type MuscleGroup = string;
export interface TrainingState {
    fatigueScore: bigint;
    weekNumber: bigint;
}
export interface SelectionStep {
    output: string;
    step: string;
    input: string;
}
export interface ReadinessItem {
    recoveryPct: bigint;
    muscleGroup: MuscleGroup;
}
export interface CoachRecommendation {
    workoutType: string;
    readiness: Array<ReadinessItem>;
    reason: string;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface SetLog {
    rpe?: bigint;
    setNumber: bigint;
    weightUsed: number;
    repsCompleted: bigint;
}
export type ExerciseId = string;
export interface UserProfile {
    experienceLevel: ExperienceLevel;
    goal: Goal;
    bodyweightKg: number;
    gender: Gender;
    restTimerSeconds: bigint;
}
export enum ExperienceLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum Gender {
    female = "female",
    male = "male"
}
export enum Goal {
    quick = "quick",
    strength = "strength",
    hypertrophy = "hypertrophy"
}
export interface backendInterface {
    getCoachRecommendation(): Promise<CoachRecommendation | null>;
    getExercises(): Promise<Array<Exercise>>;
    getPersonalBests(): Promise<Array<[string, PersonalBest]>>;
    getReadiness(): Promise<Array<ReadinessItem>>;
    getSmartMenu(workoutType: string): Promise<SmartMenuResult>;
    getTrainingState(): Promise<TrainingState | null>;
    getUserProfile(): Promise<UserProfile | null>;
    getWorkoutHistory(offset: bigint, limit: bigint): Promise<Array<WorkoutSession>>;
    logWorkout(session: WorkoutSession): Promise<Result>;
    setUserProfile(profile: UserProfile): Promise<void>;
}
import type { CoachRecommendation as _CoachRecommendation, ExerciseId as _ExerciseId, ExperienceLevel as _ExperienceLevel, Gender as _Gender, Goal as _Goal, Result as _Result, SetLog as _SetLog, SmartExercise as _SmartExercise, Timestamp as _Timestamp, TrainingState as _TrainingState, UserProfile as _UserProfile, WorkoutSession as _WorkoutSession } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getCoachRecommendation(): Promise<CoachRecommendation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachRecommendation();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachRecommendation();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercises();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercises();
            return result;
        }
    }
    async getPersonalBests(): Promise<Array<[string, PersonalBest]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalBests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalBests();
            return result;
        }
    }
    async getReadiness(): Promise<Array<ReadinessItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReadiness();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReadiness();
            return result;
        }
    }
    async getSmartMenu(arg0: string): Promise<SmartMenuResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmartMenu(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmartMenu(arg0);
            return result;
        }
    }
    async getTrainingState(): Promise<TrainingState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingState();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingState();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutHistory(arg0: bigint, arg1: bigint): Promise<Array<WorkoutSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutHistory(arg0, arg1);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutHistory(arg0, arg1);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async logWorkout(arg0: WorkoutSession): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkout(to_candid_WorkoutSession_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkout(to_candid_WorkoutSession_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ExperienceLevel_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceLevel): ExperienceLevel {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_SetLog_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SetLog): SetLog {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutSession_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutSession): WorkoutSession {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CoachRecommendation]): CoachRecommendation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrainingState]): TrainingState | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    setLogs: Array<[_ExerciseId, Array<_SetLog>]>;
    totalVolume: number;
    note: string;
    exercises: Array<_SmartExercise>;
    timestamp: _Timestamp;
    workoutType: string;
}): {
    setLogs: Array<[ExerciseId, Array<SetLog>]>;
    totalVolume: number;
    note: string;
    exercises: Array<SmartExercise>;
    timestamp: Timestamp;
    workoutType: string;
} {
    return {
        setLogs: from_candid_vec_n15(_uploadFile, _downloadFile, value.setLogs),
        totalVolume: value.totalVolume,
        note: value.note,
        exercises: value.exercises,
        timestamp: value.timestamp,
        workoutType: value.workoutType
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rpe: [] | [bigint];
    setNumber: bigint;
    weightUsed: number;
    repsCompleted: bigint;
}): {
    rpe?: bigint;
    setNumber: bigint;
    weightUsed: number;
    repsCompleted: bigint;
} {
    return {
        rpe: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.rpe)),
        setNumber: value.setNumber,
        weightUsed: value.weightUsed,
        repsCompleted: value.repsCompleted
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: _ExperienceLevel;
    goal: _Goal;
    bodyweightKg: number;
    gender: _Gender;
    restTimerSeconds: bigint;
}): {
    experienceLevel: ExperienceLevel;
    goal: Goal;
    bodyweightKg: number;
    gender: Gender;
    restTimerSeconds: bigint;
} {
    return {
        experienceLevel: from_candid_ExperienceLevel_n6(_uploadFile, _downloadFile, value.experienceLevel),
        goal: from_candid_Goal_n8(_uploadFile, _downloadFile, value.goal),
        bodyweightKg: value.bodyweightKg,
        gender: from_candid_Gender_n10(_uploadFile, _downloadFile, value.gender),
        restTimerSeconds: value.restTimerSeconds
    };
}
function from_candid_tuple_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ExerciseId, Array<_SetLog>]): [ExerciseId, Array<SetLog>] {
    return [
        value[0],
        from_candid_vec_n17(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Gender {
    return "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): ExperienceLevel {
    return "intermediate" in value ? ExperienceLevel.intermediate : "beginner" in value ? ExperienceLevel.beginner : "advanced" in value ? ExperienceLevel.advanced : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quick: null;
} | {
    strength: null;
} | {
    hypertrophy: null;
}): Goal {
    return "quick" in value ? Goal.quick : "strength" in value ? Goal.strength : "hypertrophy" in value ? Goal.hypertrophy : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutSession>): Array<WorkoutSession> {
    return value.map((x)=>from_candid_WorkoutSession_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ExerciseId, Array<_SetLog>]>): Array<[ExerciseId, Array<SetLog>]> {
    return value.map((x)=>from_candid_tuple_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SetLog>): Array<SetLog> {
    return value.map((x)=>from_candid_SetLog_n18(_uploadFile, _downloadFile, x));
}
function to_candid_ExperienceLevel_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): _ExperienceLevel {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_SetLog_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SetLog): _SetLog {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutSession_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutSession): _WorkoutSession {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    setLogs: Array<[ExerciseId, Array<SetLog>]>;
    totalVolume: number;
    note: string;
    exercises: Array<SmartExercise>;
    timestamp: Timestamp;
    workoutType: string;
}): {
    setLogs: Array<[_ExerciseId, Array<_SetLog>]>;
    totalVolume: number;
    note: string;
    exercises: Array<_SmartExercise>;
    timestamp: _Timestamp;
    workoutType: string;
} {
    return {
        setLogs: to_candid_vec_n23(_uploadFile, _downloadFile, value.setLogs),
        totalVolume: value.totalVolume,
        note: value.note,
        exercises: value.exercises,
        timestamp: value.timestamp,
        workoutType: value.workoutType
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rpe?: bigint;
    setNumber: bigint;
    weightUsed: number;
    repsCompleted: bigint;
}): {
    rpe: [] | [bigint];
    setNumber: bigint;
    weightUsed: number;
    repsCompleted: bigint;
} {
    return {
        rpe: value.rpe ? candid_some(value.rpe) : candid_none(),
        setNumber: value.setNumber,
        weightUsed: value.weightUsed,
        repsCompleted: value.repsCompleted
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: ExperienceLevel;
    goal: Goal;
    bodyweightKg: number;
    gender: Gender;
    restTimerSeconds: bigint;
}): {
    experienceLevel: _ExperienceLevel;
    goal: _Goal;
    bodyweightKg: number;
    gender: _Gender;
    restTimerSeconds: bigint;
} {
    return {
        experienceLevel: to_candid_ExperienceLevel_n32(_uploadFile, _downloadFile, value.experienceLevel),
        goal: to_candid_Goal_n34(_uploadFile, _downloadFile, value.goal),
        bodyweightKg: value.bodyweightKg,
        gender: to_candid_Gender_n36(_uploadFile, _downloadFile, value.gender),
        restTimerSeconds: value.restTimerSeconds
    };
}
function to_candid_tuple_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [ExerciseId, Array<SetLog>]): [_ExerciseId, Array<_SetLog>] {
    return [
        value[0],
        to_candid_vec_n25(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == ExperienceLevel.intermediate ? {
        intermediate: null
    } : value == ExperienceLevel.beginner ? {
        beginner: null
    } : value == ExperienceLevel.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): {
    quick: null;
} | {
    strength: null;
} | {
    hypertrophy: null;
} {
    return value == Goal.quick ? {
        quick: null
    } : value == Goal.strength ? {
        strength: null
    } : value == Goal.hypertrophy ? {
        hypertrophy: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[ExerciseId, Array<SetLog>]>): Array<[_ExerciseId, Array<_SetLog>]> {
    return value.map((x)=>to_candid_tuple_n24(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SetLog>): Array<_SetLog> {
    return value.map((x)=>to_candid_SetLog_n26(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
